provide: heroku
buildpack: nodejs
app: zazcartest
language: node_js
node_js:
- '4'
api_key:
  secure: AIP72bZnelzBwFVnEZyVCjhEEaL33mhqStFyi3Pd2n4bS5tLwmmQOkMcU3ot2BtzZ0VBksM8rqdwicX6+WWTw4cu+rF1s75jIzQVRO4879pNHzQiCu+q+ZGP47iHI+t+/nveeMkZB+weAubfpRpALI+fd/c8Nsl3wDGP73KkLKnwmF2PMZG7w4gJVg1qXdQoFG8KsFknGmd/PnqSZXMbxXOFTZqKw9tVJEOSvZW0YZ4ePqLF8Ae/wiO5d4wJJDoDhGuyQc2Yw5Fnb1N0Dq0VAay3E1twATbk9vML4iNbzbLJ/E95UfVlpyqjpEvWjxuSiMnIQWBoBzvoQLXI+iIGi4OnW7spe+HQ6nb2T4sTI6HC04aAslN8uziqYsRKDQyEOI8fPxmQHb9f+692XTD7lMWI48wa4f/i3ZfmYfqkcKfBmmUdVoQwceMEDnYwglsvuFF2nH6vOWO3lwIo5J+QzzBl327wZ2dUGSdpu9sOmtZ2q6U2+XSUniDCazEBByGWXJYEKVHSSAoZrp18XwNLgscii/qF4jHqaon/vRa4EYI+PXa+RSPTlJNgFrJt5D8l2XL/UzucKYc+NkprGIlZZm/+SDAhONjchrLHZWoxFc5myaYqNZg98JXFpmC0lH5hSm/5aIcq5FJpmi89K6lNzT9NrtJYEBxscGNvXneHZDw=
sudo: required
dist: trusty
matrix:
  fast_finish: true
before_install:
- npm config set spin false
- npm install -g npm@^2
install:
- npm install
script:
- npm run test
run:
- webpack --progress -p
- npm start
