sudo: required
dist: trusty
language: node_js
node_js:
  - "0.12"
matrix:
  fast_finish: true
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
install:
  - npm install
script:
  - npm run test
