language: node_js
node_js:
- '4'
deploy:
  provide: heroku
  api_key:
    secure: T5ozTINQpqZ7d7Pooz2dOiHGRN20plYBm8mVHgXl9VZviph525WZYrvfDOtWH62K4fC4dKlkfExJULJCPzI5R7LAXwT8kOnvYwsCYsRmuItijZkbpiLpYTpk0NSjXbB8wy/7f495YtnKfRpejhCIkIXWRMjBGcQ08pA7hZTgaumjjZrrFeeIEl9/SAZR0yigpSt/GE51NJ3PIg/qsy7G9QS+tYyvES5BeAb6hkOyjwuUCRf4i6HPmUf3AmWzgagK4tUFA1CvJZFtWtEjQw9Kn4fBRnw73EzeYfQHMJ5dmKKZXsQMK3rDF06avx8qQLqdrwxiI403m/Kyc9SrNfxlkOLN5ypvX0VStpgDHSyqtgpXmoN+w+wh547J6Xdp/3an0/h0WoINwFEH7BPEtpb0K1HqOp56CBwgLpiucynMq8UUmg78a7ufKzMjNjIFFLW1x8/YrYR8n2ZHNM2aCDat/89ctK9/hmMIsU2GKyS3T4bHplHPqrxogunOgoLWIEWoT+TLgxXAGj0NE/HmV9x50TDH6EKa9dsHJKfzUY7tZ+Ce/H/2sqfS6uKF0W5G8Dy+QUSNP5mvjoyauuBzjTDqfRn7hLnuheoxNjFzlgpLDMUJkpM+NlvjpRN9sA6rUzKw37YcXyW4ZH9Qs6E/45h0SJUCMg5v3oS0CC4QZ5xAG+4=
  on:
    repo: rodrigoagostin/react-dribbble
  before_install:
  - npm config set spin false
  - npm install -g npm@^2
  install:
  - npm install
  script:
  - npm run test
