language: node_js
node_js:
  - '4'
deploy:
  provide: heroku
  api_key:
    secure: B/mUEUlu/RzCBr5VsItSKWn491/cVRMshvJ9FsCp/EbeIndy6oJQk4ObD63NK2WxvH9Lu2VM368tUCSdhWmnIABbulJFM9GpWTgmAw9BjJ+B+O37dMaktQaBlvOVjajr3+xuaNjY5sjO+jaRiMPzMYmV7yv2OP+bTmYqE/KG57hxZqDC93iGph3q3DOznCPyfEP2eo3942dm4d98UZItL57WdrZ31MVFwnh41go86+4FtnF0lcdBY3DrB/E4y9u693wVd93lfe3EGe/o/o7yn+gF+Xys6IGryzoltzgKdtL8FYIGZDgjSzQ/+YjEbJHMC48N4yW84a66JAmYjK46wAHzZWk2LSTxxeUCyvqqYQgPtNWqELu6Uvy9pQuvajMlMSj0Hj+YrQTC1PxPYJ4ylpLKrgVBQQs/phsiCYk01WChF1hgjsivLQoQdFWk4jUoYoNSTrw7MEk6sdrL0rmiWnscJTxYMS1NF4yZSSWNUWjg4gUay1WeYCrLke+XlpkBwMMZIjwpy9iBWioohl0FAoFPgMAvzVIGjK3ksnmursqm1VXTWTTGNxLC/ufhO9ZNybKNIW0/EzP+fmivOa1AN8Trv/vntw9e00LaFVE8SBbslxFn36dJFhGRHNoc9ImY+x6xIS/kVGrnsf/9e9fSgXkBTLNNc8aTHkOCnKRzHrc=
  app: zazcartest
  on:
    all_branches: true
  before_install:
    - npm config set spin false
    - npm install -g npm@^2
  install:
    - npm install
  script:
    - npm run test
  run:
    - webpack --progress -p
    - npm start
